import Footer from "@/components/Footer";
import CoverImage from "@/components/CoverImage";

export const metadata = { title: "About", description: "Zameett provides fashion design and product development across apparel categories, with specialist modest-wear sampling and manufacturing support from Pakistan.", alternates: { canonical: "/about" } };

export default function About(){return <>
  <header className="page-hero about-hero"><div className="inner"><p className="crumb"><a href="/">Home</a> &nbsp;/&nbsp; About</p><h1>Complete fashion development. <em>Specialist modest-wear expertise.</em></h1><p>Zameett is a Pakistan-based fashion design and product-development studio providing original fashion concepts, technical flats, production-ready tech packs, textile print design and specialist modest-wear development support for brands worldwide.</p><div className="page-hero-proof"><span>Pakistan based</span><span>Multi-category design</span><span>Modest-wear production specialty</span></div></div></header>
  <section className="about about-premium" id="our-story"><div className="inner"><div className="reveal"><p className="s-tag">About Zameett</p><h2 className="s-title">Broad design capability, <em>focused production experience.</em></h2><p className="s-body">Our design and technical-development services are available for modest and contemporary fashion categories. These include womenswear, menswear, childrenswear, streetwear, activewear, dresses and outerwear.</p><p className="s-body">Modest wear remains our key specialty. Experience with abayas, kaftans, modest dresses, layering, drape, coverage and embellishment placement allows us to provide more focused support to modest-fashion brands.</p><div className="values"><div className="val"><h3>Defined scope</h3><p>Deliverables, formats, revisions and exclusions are confirmed before work starts.</p></div><div className="val"><h3>Approval records</h3><p>Technical files, materials and samples move through documented review points.</p></div><div className="val"><h3>Flexible service level</h3><p>Choose design only, sampling, or a reviewed production route.</p></div><div className="val"><h3>Project-specific MOQ</h3><p>Minimums depend on garment, material, colour, embellishment and supplier requirements.</p></div></div></div><div className="about-grid reveal"><div className="about-ph"><CoverImage src="/images/30.jpeg" alt="Fabric and colour development references" /></div><div className="about-ph"><CoverImage src="/images/14.jpeg" alt="Fashion technical design development" /></div><div className="about-ph wide"><CoverImage src="/images/27.jpeg" alt="Finished fashion collection development reference" /></div></div></div></section>
  <section className="experience about-responsibility"><div className="inner"><div className="exp-photos reveal"><div className="exp-ph tall"><CoverImage src="/images/13.jpeg" alt="Garment development workspace" /></div><div className="exp-ph"><CoverImage src="/images/31.jpeg" alt="Embroidery and surface-design development" /></div></div><div className="reveal"><p className="s-tag">Who Does What</p><h2 className="s-title">Responsibility is confirmed <em>before the project begins.</em></h2><div className="about-scope-list"><article><h3>Zameett-led work</h3><ul><li>Brief development and client communication</li><li>Creative and technical-design deliverables in the agreed scope</li><li>Version control, feedback records and approvals</li><li>Project coordination stated in the proposal</li></ul></article><article><h3>Scope-dependent specialists</h3><ul><li>Fabric, trims, labels and packaging suppliers</li><li>Pattern, sampling or production facilities where required</li><li>Printing, embroidery and specialist embellishment</li><li>Testing, freight, customs and delivery providers</li></ul></article></div><p className="s-body">The quotation identifies which activities are delivered directly by Zameett and which rely on reviewed third parties. Supplier capability, confidentiality and responsibility are considered for the specific project.</p></div></div></section>
  <section className="about-identity"><div className="inner"><div><p className="s-tag">Meet the Co-Founders</p><h2 className="s-title">Strategy and fashion expertise, <em>working together.</em></h2></div><div><p>Ahad Mubashir leads business strategy, operations and marketplace systems. Zameet Mubashir leads fashion design, technical review and creative-team coordination.</p><p><a href="/about/founders">Meet Zameett's co-founders →</a></p></div></div></section>
  <section className="about-identity"><div className="inner"><div><p className="s-tag">Working Internationally</p><h2 className="s-title">A clear scope for <em>every project route.</em></h2></div><div><p>Zameett operates from Pakistan and works with clients internationally. Specific supplier, sampling and manufacturing responsibilities are confirmed in each written proposal.</p><p><a href="/disclaimer">Read our website and service information notice →</a></p></div></div></section>
  <section className="clients about-clients"><div className="inner"><div><p className="s-tag">Who We Support</p><h2 className="s-title">Fashion brands at <em>different development stages.</em></h2><p className="s-body">We work with founders, independent designers, boutiques and growing labels that need clearly scoped design, technical development, sampling or reviewed modest-wear production support.</p></div><div className="c-list"><div className="c-item"><div className="c-dot">01</div><div><h3>New brands</h3><p>Turn references and product ideas into a controlled development brief.</p></div></div><div className="c-item"><div className="c-dot">02</div><div><h3>Independent designers</h3><p>Commission design and technical files without a manufacturing commitment.</p></div></div><div className="c-item"><div className="c-dot">03</div><div><h3>Boutiques</h3><p>Review private-label and modest-wear product routes against quantity and capacity.</p></div></div><div className="c-item"><div className="c-dot">04</div><div><h3>Growing labels</h3><p>Improve documentation, sampling controls and production readiness.</p></div></div></div></div></section>
  <section className="cta page-cta"><p className="s-tag">Work With Us</p><h2 className="s-title">Start with a clear brief.<br /><em>Build from approved decisions.</em></h2><p className="cta-sub">We aim to respond within one business day with the questions needed to scope your project.</p><div className="cta-btns"><a href="/contact#get-in-touch" className="btn btn-gold">Start Your Project →</a><a href="/services" className="btn btn-outline-ivory">View Services</a></div></section><Footer />
</>}
