import PortfolioGallery from "@/components/PortfolioGallery";
import AutoReviews from "@/components/AutoReviews";
import Footer from "@/components/Footer";
import CoverImage from "@/components/CoverImage";
import JsonLd from "@/components/JsonLd";

const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [
  { "@type": "ListItem", position: 1, name: "Home", item: "https://zameett.com/" },
  { "@type": "ListItem", position: 2, name: "Portfolio", item: "https://zameett.com/portfolio" },
] };

export const metadata = { title: "Portfolio", description: "Selected Zameett fashion design, technical development, sampling and modest-wear portfolio references.", alternates: { canonical: "/portfolio" }, openGraph: { title: "Fashion Design & Modest-Wear Portfolio | Zameett", description: "Selected fashion design, technical-development, sampling and modest-wear references from Zameett.", url: "/portfolio", images: [{ url: "/images/velvet-caftan.jpeg", width: 877, height: 1280, alt: "Maroon velvet caftan development reference" }] }, twitter: { card: "summary_large_image", title: "Fashion Design & Modest-Wear Portfolio | Zameett", description: "Selected fashion design, technical-development, sampling and modest-wear references from Zameett.", images: ["/images/velvet-caftan.jpeg"] } };

export default function Portfolio() { return <>
  <JsonLd data={breadcrumbSchema} />
  <header className="page-hero portfolio-hero"><div className="inner"><p className="crumb"><a href="/">Home</a> &nbsp;/&nbsp; Portfolio</p><h1>Selected <em>development work.</em></h1><p>A curated set of fashion concepts, technical-development references, samples and finished modest-wear directions.</p><div className="page-hero-proof"><span>Design direction</span><span>Technical development</span><span>Sampling references</span></div></div></header>
  <section className="pf-feature portfolio-feature"><div className="inner"><div className="pff-media"><span className="pff-badge">Featured Development Reference</span><CoverImage src="/images/velvet-caftan.jpeg" alt="Maroon velvet caftan gown" objectPosition="center 22%" sizes="(max-width: 960px) 100vw, 55vw" priority /></div><div className="pff-copy"><p className="s-tag">Luxury Velvet Kaftan</p><h2>From concept to <em>sample direction.</em></h2><p><strong>Brief:</strong> Develop a formal modest silhouette with a rich evening finish and controlled embellishment placement.</p><p><strong>Zameett&apos;s role:</strong> Design direction, material review, detail placement and sample-stage development as shown in the approved project scope.</p><p><strong>Development focus:</strong> Drape, border scale, waist treatment, coverage and a finish suitable for formal styling.</p><div className="pff-meta"><div className="m"><b>Velvet</b><span>Material direction</span></div><div className="m"><b>Gota</b><span>Border detail</span></div><div className="m"><b>Sample</b><span>Approval stage</span></div></div></div></div></section>
  <section className="portfolio-disclosure"><div className="inner"><p><strong>Portfolio note:</strong> Selected projects are displayed with client permission or as Zameett studio references. Some branding and commercially sensitive details have been removed to protect client confidentiality. The role label on each item explains the work represented; not every project includes every service.</p></div></section>
  <section className="pf-section portfolio-gallery-section" id="portfolio-gallery"><div className="inner"><PortfolioGallery /></div></section>
  <div className="photo-break"><CoverImage src="/images/13.jpeg" objectPosition="center 30%" alt="Fashion garment development workspace" /><div className="pb-overlay"><div className="pb-content"><p className="pb-tag">Controlled Development</p><h2 className="pb-h">A clear record from brief to approval.</h2><p className="pb-p">The project proposal identifies which stages Zameett performs directly and where reviewed specialist suppliers or facilities are involved.</p><a href="/contact#get-in-touch" className="btn btn-gold">Start Your Project →</a></div></div></div>
  <section className="testimonials portfolio-testimonials"><div className="inner"><div className="t-head reveal"><p className="s-tag">Client Feedback</p><h2 className="s-title">What clients say about <em>the working process.</em></h2></div><AutoReviews /></div></section>
  <section className="cta page-cta"><p className="s-tag">Discuss Your Collection</p><h2 className="s-title">Start with the right <em>development route.</em></h2><p className="cta-sub">Share your category, style count, quantity and target date. We will recommend design only, sampling or a reviewed production scope.</p><div className="cta-btns"><a href="/contact#get-in-touch" className="btn btn-gold">Start Your Project →</a><a href="/services" className="btn btn-outline-ivory">View Services</a></div></section>
  <Footer />
</>; }
