export const SOLUTIONS = [
  {
    slug: "modest-fashion-manufacturer",
    keyword: "Modest fashion manufacturer",
    eyebrow: "Modest-Wear Production Partner",
    title: "A Modest Fashion Manufacturer Built for Brand Owners",
    titleAccent: "Built for Brand Owners",
    description:
      "Design, sampling and production for abayas, kaftans, modest dresses and coordinated collections, managed in Pakistan and shipped worldwide.",
    cover: "/services/manufacturing-1.jpeg",
    gallery: ["/services/manufacturing-1.jpeg", "/images/21.jpeg", "/images/25.jpeg"],
    contactValue: "Full Manufacturing (Design to Delivery)",
    fit: "Independent designers, boutique owners and growing modest-fashion labels that need one point of project coordination from concept to delivery.",
    timeline: "Sampling usually takes 2–4 weeks after design approval. Production timing is confirmed with your quote and depends on quantity, fabric and embellishment.",
    moq: "Flexible, low-quantity launches are welcome. MOQ is confirmed per style after we review fabric, trims and construction.",
    deliverables: ["Design and production-ready tech packs", "Fabric, trim and label sourcing", "Prototype sampling and revisions", "Bulk production, quality checkpoints and confirmed delivery options"],
    process: ["Share your collection brief, references and target quantity.", "Approve the design direction, specifications and transparent quote.", "Review a physical sample before bulk production begins.", "Approved garments move through the agreed quality checkpoints, packing and confirmed delivery handover."],
    faqs: [
      ["Do you only manufacture modest clothing?", "Modest fashion is our speciality, including abayas, kaftans, scarves, dresses and modest separates. That focus helps us protect drape, coverage and proportion."],
      ["Can you work from reference images?", "Yes. We can develop an original direction from references, sketches or an early idea, then document it in a production-ready tech pack."],
      ["Can you ship internationally?", "Yes. We work with clients worldwide and include the delivery route and estimate in your project quote."],
      ["Will I approve a sample first?", "Yes. Bulk production starts only after the sample and relevant specifications have been approved."],
    ],
  },
  {
    slug: "abaya-manufacturer-pakistan",
    keyword: "Abaya manufacturer in Pakistan",
    eyebrow: "Specialist Abaya Production",
    title: "Abaya Manufacturer in Pakistan for Global Modest Brands",
    titleAccent: "for Global Modest Brands",
    description:
      "Specialist abaya design and manufacturing in Pakistan, from clean everyday silhouettes to layered, embroidered and embellished collections.",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "Abaya labels and designers who need accurate modest proportions, fabric-aware construction and reliable communication through sampling and production.",
    timeline: "A first sample commonly takes 2–4 weeks after the design and materials are approved. Complex handwork can require additional time.",
    moq: "Small-batch abaya production is available. Final MOQ depends on the fabric, colour, embellishment method and number of sizes.",
    deliverables: ["Abaya design development and technical specifications", "Fabric and embellishment sourcing", "Fit sample with revision round", "Private-label production and quality inspection"],
    process: ["Send your sketches, references or collection mood board.", "We define silhouette, sizing, fabric and embellishment details.", "A sample is produced for fit and finish approval.", "Approved abayas move into production, QC and international delivery."],
    faqs: [
      ["What types of abayas can you manufacture?", "We support open and closed abayas, kaftan-inspired silhouettes, layered styles, bias cuts and embroidered or beaded statement pieces."],
      ["Can you source nida and other abaya fabrics?", "Yes. Fabric choices are proposed around opacity, drape, climate, finish and your target price point."],
      ["Do you offer custom sizing?", "Yes. We can work with your size chart or help develop one for your target market."],
      ["Can you add my brand labels?", "Yes. Woven labels, care labels, hangtags and packaging can be included in the production scope."],
    ],
  },
  {
    slug: "private-label-modest-clothing-manufacturer",
    keyword: "Private-label modest clothing manufacturer",
    eyebrow: "Your Label, Production Ready",
    title: "Private-Label Modest Clothing Manufacturing, End to End",
    titleAccent: "End to End",
    description:
      "Launch a branded modest collection with custom labels, packaging, sampling and production handled through one specialist team.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg", "/images/26.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "New and established brands that want original modest garments produced under their own name without building a fragmented supplier network.",
    timeline: "Allow approximately 3–5 weeks for development and sampling, followed by a production schedule based on quantity and custom branding requirements.",
    moq: "Low-volume private-label runs are considered. Labels and packaging suppliers may carry separate minimums, which are disclosed before approval.",
    deliverables: ["Original garment development", "Custom woven and care labels", "Branded hangtags and packaging options", "Sampling, production, QC and export support"],
    process: ["Define your customer, price point and collection direction.", "Select designs, materials and branding components.", "Approve the garment sample and label placement.", "We produce, inspect, pack and ship your branded order."],
    faqs: [
      ["Is this white label or fully custom?", "Our private-label service is built around custom development. We can tailor the scope to your designs, branding and budget."],
      ["Can you help if I do not have tech packs?", "Yes. Tech-pack development can be included so the final product is properly documented before sampling."],
      ["Can packaging be customised?", "Yes. Depending on quantity, options can include branded bags, boxes, tissue, stickers, tags and insert cards."],
      ["Who owns the branding?", "Your brand name and supplied brand assets remain yours. Project-specific file ownership is confirmed in your written quote."],
    ],
  },
  {
    slug: "low-moq-clothing-manufacturer-pakistan",
    keyword: "Low MOQ clothing manufacturer Pakistan",
    eyebrow: "Start Small, Scale Confidently",
    title: "Low-MOQ Modest-Wear Manufacturer in Pakistan for Emerging Brands",
    titleAccent: "for Emerging Brands",
    description:
      "Small-batch modest-wear manufacturing for emerging brands that need professional sampling, transparent quantity planning and a controlled path to scale.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/images/22.jpeg", "/images/27.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Founders testing a modest-wear capsule, boutique owners launching exclusives and designers who prefer controlled inventory over a large opening order.",
    timeline: "Sampling is generally 2–4 weeks. Small-batch production timing is quoted after material availability and the final order breakdown are confirmed.",
    moq: "MOQ is assessed per style rather than advertised as one misleading number. Simple styles and shared fabrics usually allow the most flexible quantities.",
    deliverables: ["Feasibility and quantity planning", "Sample development before production", "Small-batch cutting and stitching", "Quality checks with a scale-up plan for reorders"],
    process: ["Tell us the styles, sizes, target units and launch date.", "We simplify materials or construction where it protects your budget.", "Approve a sample and final per-unit quote.", "Launch the small run, then reorder with the specifications already established."],
    faqs: [
      ["What is your exact minimum order?", "It varies by garment, fabric and customisation. Share the style and target quantity and we will give you a practical answer instead of a generic MOQ."],
      ["Can I mix sizes and colours?", "Usually yes, within material and cutting constraints. We confirm the workable breakdown in the quote."],
      ["Will low MOQ cost more per piece?", "Often, because setup and sourcing costs are spread across fewer units. We show the trade-off clearly and suggest ways to improve efficiency."],
      ["Can I scale the same style later?", "Yes. Once specifications and the approved sample are established, repeat production is faster and easier to plan."],
    ],
  },
  {
    slug: "fashion-tech-pack-design-service",
    keyword: "Fashion tech-pack design service",
    eyebrow: "Production-Ready Technical Development",
    title: "Fashion Tech-Pack Design Service for Clearer Production",
    titleAccent: "for Clearer Production",
    description:
      "Detailed, editable fashion tech packs that translate your concept into clear construction, measurements, materials and factory instructions.",
    cover: "/images/techpack.jpeg",
    gallery: ["/images/techpack.jpeg", "/services/abaya-1.jpeg", "/images/14.jpeg"],
    contactValue: "Design & Tech Packs Only",
    fit: "Fashion founders and designers who need a manufacturer-ready specification pack before sampling or requesting reliable production quotes.",
    timeline: "Most single-style tech packs take 5–10 business days after the brief is complete. Multi-style collections are scheduled in stages.",
    moq: "Tech-pack projects are scoped per style or collection. Manufacturing MOQ is separate and confirmed only when physical production is requested.",
    deliverables: ["Front and back technical flats", "Construction and seam call-outs", "Bill of materials and colour references", "Measurement chart, artwork placement and export files"],
    process: ["Send sketches, references and any existing measurements.", "We clarify construction, fit, materials and file requirements.", "Review the draft and consolidated production notes.", "Receive the final editable source and production-ready PDF package."],
    faqs: [
      ["What do I need to provide?", "A sketch, reference images or a clear written idea is enough to begin. Existing size charts, logos and material preferences are helpful but not mandatory."],
      ["Are the files editable?", "Editable source-file delivery is available and the included formats are stated clearly in your quote."],
      ["Can my own factory use the tech pack?", "Yes. The purpose is to create a clear handoff that a professional apparel factory can quote and sample from."],
      ["Does a tech pack guarantee a perfect first sample?", "No document can remove all sampling variables, but a detailed pack reduces ambiguity, prevents avoidable errors and makes revisions traceable."],
    ],
  },
  {
    slug: "abaya-tech-pack-designer",
    keyword: "Abaya tech-pack designer",
    eyebrow: "Technical Design for Modest Wear",
    title: "Abaya Tech-Pack Designer Who Understands the Silhouette",
    titleAccent: "Who Understands the Silhouette",
    description:
      "Production-ready abaya tech packs covering proportion, construction, measurement specifications, embroidery and embellishment placement with modest-wear expertise.",
    cover: "/services/abaya-2.jpeg",
    gallery: ["/services/abaya-2.jpeg", "/services/abaya-1.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Fashion Tech Pack (Abaya / Kaftan / Modest Wear)",
    fit: "Abaya designers who need their creative intent translated accurately for factories that may not understand modest-wear drape, length and detailing.",
    timeline: "A standard abaya tech pack usually takes 5–10 business days. Multi-piece sets or heavy embellishment are scoped separately.",
    moq: "There is no production MOQ for design work. You can commission a single abaya style before expanding the collection.",
    deliverables: ["Abaya-specific technical flats", "Length, ease and coverage measurements", "Embroidery, bead and placement specifications", "Bill of materials, colourways and factory PDF"],
    process: ["Share the silhouette and embellishment references.", "We resolve opening, sleeve, layering and modesty requirements.", "Review technical flats and specification details.", "Receive a production-ready technical package for quotation and sampling."],
    faqs: [
      ["Can you document hand embroidery and beadwork?", "Yes. We can specify placement, scale, stitch or bead references and artwork call-outs based on the agreed scope."],
      ["Can you create a size chart?", "Yes. We can adapt your chart or develop measurements around the intended market and fit direction."],
      ["Do you design kaftans and bisht styles too?", "Yes. The same specialist service covers kaftans, bisht-inspired pieces and other modest silhouettes."],
      ["Can you work with my manufacturer during sampling?", "Sampling support can be added so technical questions and revision notes are handled consistently."],
    ],
  },
  {
    slug: "editable-fashion-tech-pack-template",
    keyword: "Editable fashion tech-pack template",
    eyebrow: "Reusable Product-Development System",
    title: "Editable Fashion Tech-Pack Templates Made for Your Workflow",
    titleAccent: "Made for Your Workflow",
    description:
      "Customisable fashion tech-pack templates with clear pages for flats, measurements, BOMs, colourways, artwork and revision tracking.",
    cover: "/digital/p1-1.jpeg",
    gallery: ["/digital/p1-1.jpeg", "/digital/p1-2.jpeg", "/digital/p1-3.jpeg"],
    contactValue: "Design & Tech Packs Only",
    fit: "In-house designers, fashion students and growing labels that want a repeatable, editable structure for future product development.",
    timeline: "A customised template is typically prepared within 3–7 business days after your format, branding and category needs are confirmed.",
    moq: "Purchase or commission one reusable template and duplicate it for future styles according to the included licence.",
    deliverables: ["Editable, brand-ready page system", "Measurement and bill-of-material tables", "Colourway, artwork and label sections", "Revision log plus PDF export layout"],
    process: ["Choose your garment category and preferred software.", "Share your logo, colours and existing factory requirements.", "Review the page structure and sample style.", "Receive the editable master template and usage guidance."],
    faqs: [
      ["Which editable formats are available?", "Available formats depend on the template or custom scope. Tell us your software before ordering so compatibility is confirmed."],
      ["Is this a completed tech pack?", "A template is the reusable framework. If you need a finished pack for a specific garment, choose our tech-pack design service."],
      ["Can you add my logo and brand colours?", "Yes. Custom branding and additional category-specific pages can be included."],
      ["Can my team reuse it?", "Yes, subject to the licence provided with the product. We can also quote a team-specific custom template."],
    ],
  },
  {
    slug: "custom-textile-pattern-designer",
    keyword: "Custom textile pattern designer",
    eyebrow: "Original Prints for Distinctive Collections",
    title: "Custom Textile Pattern Designer for Fashion Brands",
    titleAccent: "for Fashion Brands",
    description:
      "Original seamless repeats and placement prints developed around your brand, garment, colour story and production requirements.",
    cover: "/services/textile-1.jpeg",
    gallery: ["/services/textile-1.jpeg", "/services/textile-2.jpeg", "/services/textile-3.jpeg"],
    contactValue: "Custom Seamless Textile Patterns",
    fit: "Fashion labels and textile buyers who want a recognisable print language instead of generic stock artwork used by competing brands.",
    timeline: "Most single-pattern projects take 5–10 business days. Collections, complex hand-drawn motifs and multiple colourways require a longer schedule.",
    moq: "Design work can be commissioned per artwork. Fabric-printer minimums are separate and depend on the chosen supplier.",
    deliverables: ["Original motifs and seamless repeat", "Print scale and production repeat tile", "Approved colourways", "High-resolution, layered production files"],
    process: ["Share your brand mood, garment type and colour direction.", "Approve the motif direction and initial composition.", "Review the repeat, scale and colourways.", "Receive production-ready files for your printer or manufacturer."],
    faqs: [
      ["Will the design be seamless?", "Yes, when the project is for an all-over repeat. Placement prints are built to the specified garment panel instead."],
      ["Can you match Pantone colours?", "We can include colour references, but final fabric colour should always be confirmed through a physical strike-off from the printer."],
      ["Do I receive source files?", "Layered source-file delivery is available and the exact formats are confirmed before the project begins."],
      ["Can you create several colourways?", "Yes. Additional colourways can be developed after the master pattern and palette direction are approved."],
    ],
  },
  {
    slug: "fashion-sampling-services",
    keyword: "Garment sampling and fitting service",
    eyebrow: "Approve Before You Produce",
    title: "Garment Sampling and Fitting for Modest Fashion Brands",
    titleAccent: "for Modest Fashion Brands",
    description: "Prototype development, fit review and documented corrections for modest-fashion collections before bulk production.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/images/18.jpeg", "/images/23.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Brands with designs or tech packs ready that need a physical prototype, specialist fit review and a controlled revision round.",
    timeline: "A first sample generally takes 2–4 weeks after specifications and materials are approved.",
    moq: "A single development sample can be reviewed before deciding whether to continue into a broader sampling or production scope.",
    deliverables: ["Prototype in approved development materials", "Measurement and fit review", "Construction, finish and modesty checks", "Consolidated sample comments"],
    process: ["Share the latest tech pack or design brief.", "Confirm materials, measurements and review criteria.", "Assess the prototype through one organised correction record.", "Approve the sample or begin a scoped revision round."],
    faqs: [
      ["Can you sample a tech pack made by another designer?", "Yes. We first audit it for missing measurements, materials or construction decisions."],
      ["Do you fit-test modest garments differently?", "Yes. We review movement, opacity, length, sleeve reach, opening coverage and layering."],
      ["Is the sample made in final fabric?", "Where practical, yes. Any development substitute is proposed and disclosed before sampling."],
      ["Can you manage revisions with my factory?", "Technical revision support can be scoped when the factory follows one controlled comment and tech-pack process."],
    ],
  },
  {
    slug: "fabric-sourcing-modest-fashion",
    keyword: "Fabric sourcing for modest fashion",
    eyebrow: "Material Decisions Made Clear",
    title: "Fabric Sourcing for Abayas and Modest-Wear Collections",
    titleAccent: "for Abayas and Modest-Wear Collections",
    description: "Fabric and trim sourcing guided by opacity, drape, climate, care, embellishment, target price and quantity.",
    cover: "/images/25.jpeg",
    gallery: ["/images/25.jpeg", "/images/24.jpeg", "/services/textile-2.jpeg"],
    contactValue: "Fabric & Trim Sourcing",
    fit: "Labels that know the silhouette but need commercially suitable fabric, lining, trims or embellishment bases before sampling.",
    timeline: "Initial options can usually be prepared in 5–10 business days; custom materials require more supplier lead time.",
    moq: "Minimums vary by quality, colour and finish. Stock materials offer the most flexibility; custom dyeing and printing require more quantity.",
    deliverables: ["Shortlisted material options", "Composition and use guidance", "Supplier MOQ and lead-time information", "Swatch coordination where included"],
    process: ["Define use, target price, colour and performance.", "Review practical stock or custom routes.", "Check swatches, opacity, drape and construction compatibility.", "Approve the quality reference before purchasing."],
    faqs: [
      ["Can you source common abaya fabrics?", "Yes. The recommendation follows drape, opacity, climate, care and price rather than the fabric name alone."],
      ["Can you guarantee an exact screen colour?", "No. Final colour should be approved on a physical swatch or strike-off."],
      ["Do fabric suppliers have separate MOQs?", "Usually. We disclose the relevant roll, metre, colour or print minimum before approval."],
      ["Can I use the fabric with my own manufacturer?", "Yes when the agreed sourcing scope supports a direct handoff."],
    ],
  },
  {
    slug: "fashion-production-management",
    keyword: "Fashion production management service",
    eyebrow: "One Controlled Production Workflow",
    title: "Fashion Production Management from Sample to Shipment",
    titleAccent: "from Sample to Shipment",
    description: "Milestone, supplier, approval and quality-control coordination for modest-fashion brands that need an accountable workflow.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/services/manufacturing-1.jpeg", "/images/26.jpeg"],
    contactValue: "Production Management",
    fit: "Growing labels with several styles, suppliers or approval stages that need clearer timelines and one documented source of truth.",
    timeline: "The schedule follows the approved critical path and depends on sampling, material lead time, quantity and supplier capacity.",
    moq: "Management has no universal MOQ, but manufacturers and material suppliers may each have minimums.",
    deliverables: ["Critical path and milestone tracking", "Supplier and approval coordination", "Purchase-order and specification checks", "Quality and shipment readiness"],
    process: ["Audit files, samples and open decisions.", "Build responsibilities and the critical path.", "Track approvals, risks and updates.", "Close production with inspection and shipment handover."],
    faqs: [
      ["Can you manage a factory I already use?", "Potentially, after reviewing the relationship, files, history and access required."],
      ["Does management include manufacturing cost?", "No. Management, manufacturing, materials, testing and freight are separated in the proposal."],
      ["How are delays handled?", "Risks are logged against the critical path with an owner and next decision."],
      ["Do you guarantee a launch date?", "We provide a realistic schedule after materials, samples and capacity are confirmed."],
    ],
  },];

export function getSolution(slug) {
  return SOLUTIONS.find((solution) => solution.slug === slug);
}
