export const SOLUTIONS = [
  {
    slug: "abaya-manufacturer-pakistan",
    keyword: "Abaya manufacturer in Pakistan",
    seoTitle: "Abaya Manufacturer in Pakistan for Modest Brands",
    eyebrow: "Specialist Abaya Production",
    title: "Abaya Manufacturer in Pakistan for Global Modest Brands",
    titleAccent: "for Global Modest Brands",
    description:
      "Specialist abaya design and manufacturing in Pakistan, from clean everyday silhouettes to layered, embroidered and embellished collections.",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "Abaya labels and designers who need accurate modest proportions, fabric-aware construction and reliable communication through sampling and production.",
    timeline: "Sampling and production timing is confirmed for the project after the design, materials, embellishment, quantity and supplier route are reviewed.",
    moq: "Manufacturing MOQ is project-specific and depends on the garment, fabric, colour, embellishment, trims, packaging, size mix and suppliers.",
    deliverables: ["Abaya design development and technical specifications", "Fabric and embellishment sourcing support", "Fit-sample route with agreed revisions", "Coordinated private-label production and quality checkpoints"],
    process: ["Send your sketches, references or collection mood board.", "We define silhouette, sizing, fabric and embellishment details.", "A sample is produced for fit and finish approval.", "Approved abayas move into production, QC and international delivery."],
    faqs: [
      ["What types of abayas can you manufacture?", "We support open and closed abayas, kaftan-inspired silhouettes, layered styles, bias cuts and embroidered or beaded statement pieces."],
      ["Can you source nida and other abaya fabrics?", "Yes. Fabric choices are proposed around opacity, drape, climate, finish and your target price point."],
      ["Do you offer custom sizing?", "Yes. We can work with your size chart or help develop one for your target market."],
      ["Can you add my brand labels?", "Yes. Woven labels, care labels, hangtags and packaging can be included in the production scope."],
    ],
  },
  {
    slug: "private-label-modest-clothing-manufacturer",
    keyword: "Private-label modest clothing manufacturer",
    seoTitle: "Private-Label Modest Clothing Manufacturer",
    eyebrow: "Your Label, Production Ready",
    title: "Private-Label Modest Clothing Manufacturing, End to End",
    titleAccent: "End to End",
    description:
      "Launch a branded modest collection with custom labels, packaging, sampling and production handled through one specialist team.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg", "/images/26.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "New and established brands that want original modest garments produced under their own name without building a fragmented supplier network.",
    timeline: "Development, sampling and production timing is quoted after style complexity, materials, branding, quantity and supplier availability are reviewed.",
    moq: "MOQ is confirmed per project. Garment, fabric, colour, trims, labels and packaging suppliers may each create separate minimums.",
    deliverables: ["Original garment development", "Custom woven and care labels", "Branded hangtags and packaging options", "Sampling, production, QC and export support"],
    process: ["Define your customer, price point and collection direction.", "Select designs, materials and branding components.", "Approve the garment sample and label placement.", "Approved production, inspection, packing and delivery handover are coordinated within the written scope."],
    faqs: [
      ["Is this white label or fully custom?", "Our private-label service is built around custom development. We can tailor the scope to your designs, branding and budget."],
      ["Can you help if I do not have tech packs?", "Yes. Tech-pack development can be included so the final product is properly documented before sampling."],
      ["Can packaging be customised?", "Yes. Depending on quantity, options can include branded bags, boxes, tissue, stickers, tags and insert cards."],
      ["Who owns the branding?", "Your brand name and supplied brand assets remain yours. Project-specific file ownership is confirmed in your written quote."],
    ],
  },
  {
    slug: "low-moq-clothing-manufacturer-pakistan",
    keyword: "Low MOQ clothing manufacturer Pakistan",
    seoTitle: "Low-MOQ Clothing Manufacturer in Pakistan",
    eyebrow: "Start Small, Scale Confidently",
    title: "Low-MOQ Modest-Wear Manufacturer in Pakistan for Emerging Brands",
    titleAccent: "for Emerging Brands",
    description:
      "Small-batch modest-wear manufacturing for emerging brands that need professional sampling, transparent quantity planning and a controlled path to scale.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/images/22.jpeg", "/images/27.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Founders testing a modest-wear capsule, boutique owners launching exclusives and designers who prefer controlled inventory over a large opening order.",
    timeline: "Sampling and production timing is quoted after the files, material availability, construction, target quantity and size-colour breakdown are confirmed.",
    moq: "MOQ is assessed per project. Garment, fabric, colour, embellishment, trims, packaging and supplier requirements determine the workable quantity.",
    deliverables: ["Feasibility and quantity planning", "Sample development before production", "Small-batch cutting and stitching", "Quality checks with a scale-up plan for reorders"],
    process: ["Tell us the styles, sizes, target units and launch date.", "We simplify materials or construction where it protects your budget.", "Approve a sample and final per-unit quote.", "Launch the small run, then reorder with the specifications already established."],
    faqs: [
      ["What is your exact minimum order?", "It varies by garment, fabric and customisation. Share the style and target quantity and we will give you a practical answer instead of a generic MOQ."],
      ["Can I mix sizes and colours?", "Usually yes, within material and cutting constraints. We confirm the workable breakdown in the quote."],
      ["Will low MOQ cost more per piece?", "Often, because setup and sourcing costs are spread across fewer units. We show the trade-off clearly and suggest ways to improve efficiency."],
      ["Can I scale the same style later?", "Yes. Once specifications and the approved sample are established, repeat production is faster and easier to plan."],
    ],
  },
  {
    slug: "abaya-tech-pack-designer",
    keyword: "Abaya tech pack designer",
    seoTitle: "Abaya Tech Pack Design Services for Fashion Brands",
    keywords: [
      "abaya tech pack designer",
      "abaya tech pack design",
      "modest fashion tech pack",
      "kaftan tech pack",
      "abaya technical drawing",
      "fashion tech pack services",
    ],
    eyebrow: "Technical Design for Modest Wear",
    title: "Abaya Tech Pack Design for Clearer Sampling and Production",
    titleAccent: "for Clearer Sampling and Production",
    description:
      "Specialist abaya tech pack design covering technical flats, construction, measurement specifications, materials, colourways and embellishment placement for sampling and supplier quotation.",
    cover: "/services/abaya-2.jpeg",
    gallery: ["/services/abaya-2.jpeg", "/services/abaya-1.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Fashion Tech Pack (Abaya / Kaftan / Modest Wear)",
    trustPoints: ["Abaya-specific scope", "Editable files where stated", "Packages from $95"],
    fit: "Abaya and modest-fashion brands that need the silhouette, coverage, drape, openings, sleeves and embellishment direction translated into clear technical documentation.",
    timeline:
      "Published one-style packages start from 3 business days for standard complexity. Layered, heavily embellished or multi-style projects receive a confirmed schedule before payment.",
    moq:
      "Tech-pack design is commissioned per style or collection. Any later sampling or manufacturing MOQ is separate and depends on the garment, fabric, colour, embellishment, trims and supplier requirements.",
    deliverables: [
      "Front, back and required detail technical flats",
      "Construction, opening, sleeve and finishing call-outs",
      "Fabric, lining, trim and complete bill of materials",
      "Measurement specifications within the agreed size scope",
      "Embroidery, beadwork, print or embellishment placement",
      "Colourways, revision references and agreed PDF or source files",
    ],
    process: [
      "Share your sketch, references, brand direction, target customer and any known measurements.",
      "Confirm the silhouette, opening, sleeves, layering, fabric, embellishment and file scope.",
      "Review the technical flats and specification through consolidated feedback.",
      "Receive the checked final pack for supplier quotation or sampling. Manufacturing is scoped separately.",
    ],
    faqs: [
      ["What do I need to provide?", "A sketch or visual references, the target customer, garment direction and any available size information are helpful. We clarify missing decisions before confirming the scope."],
      ["Can you document hand embroidery and beadwork?", "Yes. Placement, scale, artwork and application notes can be documented within the agreed scope. Physical testing and supplier execution remain separate stages."],
      ["Can you create measurement specifications?", "We can adapt an approved chart or prepare measurement specifications within the agreed size scope. This does not include a sewing pattern or standalone grading service."],
      ["Do you design kaftans and bisht styles too?", "Yes. Kaftans, bisht-inspired pieces and related modest silhouettes can be reviewed and scoped according to their construction and detailing."],
      ["Can you answer manufacturer questions?", "The included clarification support is stated in the selected package or proposal. New design changes outside the approved scope are quoted separately."],
      ["Are sampling and manufacturing included?", "No. The tech-pack package is a design and technical-documentation service. Sampling or modest-wear manufacturing can be reviewed separately, with project-specific MOQ and timing."],
    ],
  },
  {
    slug: "editable-fashion-tech-pack-template",
    keyword: "Editable fashion tech-pack template",
    seoTitle: "Editable Fashion Tech Pack Template Service",
    eyebrow: "Reusable Product-Development System",
    title: "Editable Fashion Tech-Pack Templates Made for Your Workflow",
    titleAccent: "Made for Your Workflow",
    description:
      "Customisable fashion tech-pack templates with clear pages for flats, measurements, BOMs, colourways, artwork and revision tracking.",
    cover: "/digital/p1-1.jpeg",
    gallery: ["/digital/p1-1.jpeg", "/digital/p1-2.jpeg", "/digital/p1-3.jpeg"],
    contactValue: "Design & Tech Packs Only",
    fit: "In-house designers, fashion students and growing labels that want a repeatable, editable structure for future product development.",
    timeline: "A customised template is typically prepared within 3 to 7 business days after your format, branding and category needs are confirmed.",
    moq: "Purchase or commission one reusable template and duplicate it for future styles according to the included licence.",
    deliverables: ["Editable, brand-ready page system", "Measurement and bill-of-material tables", "Colourway, artwork and label sections", "Revision log plus PDF export layout"],
    process: ["Choose your garment category and preferred software.", "Share your logo, colours and existing factory requirements.", "Review the page structure and sample style.", "Receive the editable master template and usage guidance."],
    faqs: [
      ["Which editable formats are available?", "Available formats depend on the template or custom scope. Tell us your software before ordering so compatibility is confirmed."],
      ["Is this a completed tech pack?", "A template is the reusable framework. If you need a finished pack for a specific garment, choose our tech-pack design service."],
      ["Can you add my logo and brand colours?", "Yes. Custom branding and additional category-specific pages can be included."],
      ["Can my team reuse it?", "Yes, subject to the licence provided with the product. We can also quote a team-specific custom template."],
    ],
  },
  {
    slug: "fashion-sampling-services",
    keyword: "Garment sampling and fitting service",
    seoTitle: "Garment Sampling & Fitting Services",
    eyebrow: "Approve Before You Produce",
    title: "Garment Sampling and Fitting for Modest Fashion Brands",
    titleAccent: "for Modest Fashion Brands",
    description: "Physical garment samples, fit review and documented corrections for abayas and modest-fashion products before production decisions are made.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/images/18.jpeg", "/images/23.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Brands with a design brief or tech pack that need to test a garment physically before production. Sampling specialisation is mainly abayas, kaftans, modest dresses, scarves and coordinated modest-wear products; other apparel can be reviewed for fit.",
    timeline: "The sampling schedule is project-specific and confirmed after the files, material route, construction, embellishment, sample stage, review method and delivery destination are approved.",
    moq: "A development sample is scoped separately from manufacturing. Any later production MOQ is confirmed for the approved garment, fabric, colour, embellishment, trims, packaging and suppliers.",
    pricing: "Sampling is quoted from the garment, sample stage, material and trim requirements, sourcing work, construction complexity, embellishment, number of styles, review route and delivery destination. Scope is confirmed before payment.",
    quoteDescription: "Share the latest files, sample stage, garment categories, number of styles, materials, measurements, embellishment, review requirements and delivery country. We confirm capability, scope, schedule, assumptions and exclusions before payment.",
    trustPoints: ["Files reviewed before sampling", "Consolidated sample comments", "Approval before production"],
    deliverables: ["Design-brief or tech-pack feasibility review", "Approved material and trim route", "Physical prototype for the agreed sample stage", "Measurement, fit and modesty review record", "Construction, finish and embellishment checks", "Consolidated corrections and next-stage recommendation"],
    process: ["Share the latest tech pack or design brief, sample objective and required review date.", "Confirm materials, measurements, construction, fit criteria, sample stage, quotation and delivery assumptions before payment.", "Review the physical sample against one organised measurement, fit, coverage, construction and finish record.", "Approve the sample for its stated purpose or begin a separately scoped revision; production is not implied by sample delivery."],
    resources: [
      ["Understand the main garment sample types", "/blog/types-of-garment-samples"],
      ["Prepare a design for manufacturer review", "/blog/prepare-design-for-manufacturer"],
      ["Review a production-ready tech pack structure", "/blog/tech-pack-example"],
      ["Explore fashion tech pack services", "/services/fashion-tech-packs"],
      ["Review modest-wear development support", "/services/clothing-manufacturing"],
      ["Understand project-specific sampling quotes", "/pricing#production-title"],
    ],
    faqs: [
      ["Can you sample a tech pack made by another designer?", "Yes. We first audit it for missing measurements, materials or construction decisions."],
      ["Which garments are suitable for Zameett's sampling service?", "Physical sampling specialisation is mainly abayas, kaftans, modest dresses, scarves, layering pieces and coordinated modest-wear products. Other apparel categories can be reviewed before a scope is offered."],
      ["Do you fit-test modest garments differently?", "Modest-wear review can include movement, opacity, garment length, sleeve reach, opening coverage, layering, closure security and embellishment placement, according to the approved brief."],
      ["Is the sample made in final fabric?", "The material route is agreed before sampling. Final fabric is preferred when it is available and appropriate; any development substitute, limitation or resampling implication is disclosed in the written scope."],
      ["How long does garment sampling take?", "There is no single schedule for every product. Timing depends on file readiness, sourcing, construction, embellishment, number of styles, sample stage, review method, revisions and delivery destination. The expected stages and dependencies are confirmed for the actual project."],
      ["Does approving a sample automatically start production?", "No. A sample is approved only for its stated stage and criteria. Manufacturing capability, MOQ, bulk quotation, materials, quality checkpoints, payment terms and schedule must be confirmed separately before production."],
      ["Can you manage revisions with my factory?", "Technical revision support can be scoped when the factory follows one controlled comment and tech-pack process. Responsibilities, communication route and revision limits are confirmed before work begins."],
    ],
  },
  {
    slug: "fabric-sourcing-modest-fashion",
    keyword: "Fabric sourcing for modest fashion",
    seoTitle: "Fabric Sourcing for Modest Fashion Brands",
    keywords: [
      "fabric sourcing for modest fashion",
      "abaya fabric sourcing",
      "modest wear fabric sourcing",
      "fashion fabric sourcing service",
      "fabric and trim sourcing",
    ],
    eyebrow: "Material Decisions Made Clear",
    title: "Fabric Sourcing for Abayas and Modest-Wear Collections",
    titleAccent: "for Abayas and Modest-Wear Collections",
    description: "Fabric sourcing for abayas and modest wear, with product-specific briefs, supplier options, swatch approval, MOQ notes and sampling handover.",
    cover: "/images/25.jpeg",
    gallery: ["/images/25.jpeg", "/images/24.jpeg", "/services/textile-2.jpeg"],
    contactValue: "Fabric & Trim Sourcing",
    trustPoints: ["Product-specific material brief", "Physical approval route", "Supplier constraints recorded"],
    fit: "Abaya and modest-wear brands that have a garment direction but need the fabric, lining, trim or embellishment base translated into a commercially reviewable sourcing brief before sampling or production. Suitable categories can include abayas, kaftans, modest dresses, scarves and coordinated layering pieces.",
    timeline: "The sourcing schedule is confirmed after the garment brief, material specification, colour count, quantity, supplier route, swatch or lab-dip requirements, approval owner and delivery destination are reviewed. Custom development or testing can add stages.",
    moq: "Material minimums are project-specific and can apply by quality, colour, dye lot, print, embellishment, trim, finish or supplier. Stock and custom-development routes are reviewed separately before a quantity is confirmed.",
    pricing: "Fabric and trim sourcing is quoted from the number of styles, material categories, colours, supplier routes, swatches, custom development, document or testing requirements, approval work and delivery destination. Scope is confirmed before payment.",
    quoteDescription: "Share the garments, estimated quantities, colour count, fabric or trim direction, target price, destination, required timing and any physical reference, composition, care, opacity, drape, finish, embellishment or document requirement. We confirm the sourcing scope, approval route, assumptions and exclusions before payment.",
    deliverables: [
      "Product-specific fabric and trim requirement brief",
      "Shortlisted stock or custom-development routes",
      "Comparable supplier, MOQ and timing notes",
      "Physical swatch or colour-approval coordination where included",
      "Opacity, drape, construction and finish compatibility review",
      "Approved-reference record and sampling handover notes",
    ],
    process: [
      "Define the garment use, silhouette, climate, care, coverage, material direction, colours, quantity and target price.",
      "We review practical stock or custom routes and document supplier availability, minimums, timing, price basis and open constraints.",
      "Review the relevant physical swatch, colour reference or development sample for drape, opacity, handfeel, finish and garment compatibility.",
      "Record the approved reference, supplier terms, remaining conditions and checks required during sampling, purchasing or bulk receipt.",
    ],
    resources: [
      ["Choose fabrics for abayas and modest dresses", "/blog/fabric-guide-abayas-modest-dresses"],
      ["Use the fashion fabric-sourcing checklist", "/blog/fabric-sourcing-checklist-fashion-brand"],
      ["Build a clear garment bill of materials", "/blog/bill-of-materials-fashion"],
      ["Prepare a design for manufacturer review", "/blog/prepare-design-for-manufacturer"],
      ["Plan the right garment sample stages", "/blog/types-of-garment-samples"],
      ["Review supply-chain and quality controls", "/supply-chain"],
      ["Understand project-specific sourcing quotes", "/pricing#production-title"],
    ],
    faqs: [
      ["What information is needed for a fabric-sourcing brief?", "Share the garment category, intended use, quantity, colours, target price and timing together with any preferred composition, construction, weight, drape, opacity, stretch, finish, care, embellishment or physical reference. Unknown decisions can remain open for review rather than being guessed."],
      ["Can you source common abaya and modest-wear fabrics?", "Relevant options can be reviewed for abayas, kaftans, modest dresses, scarves and layering pieces. The recommendation follows the actual silhouette, drape, opacity, climate, care, embellishment, construction, quantity and price requirements rather than a fabric name alone."],
      ["Can you match fabric from a garment, photo or swatch?", "A physical swatch or garment gives the strongest comparison reference. A photograph can help define direction, but it cannot prove colour, handfeel, weight, composition or finish. Any proposed match remains subject to physical review and supplier availability."],
      ["Can you guarantee an exact screen colour or bulk shade?", "No. Screen colour is only directional. Final colour should be reviewed through the agreed physical swatch, lab dip or strike-off, and a bulk lot may still require comparison with the approved reference before cutting."],
      ["Do fabric and trim suppliers have separate MOQs?", "Often. Minimums can apply by base quality, colour, dye lot, print, embellishment, trim, finish or supplier. We record the applicable basis for the reviewed route instead of advertising one universal material MOQ."],
      ["Does sourcing include laboratory testing or certification?", "Not automatically. Any named test, method, laboratory, supplier document or market-compliance review must be agreed in the written scope. No sustainability, composition, performance or certification claim should be made without evidence for the selected material and project."],
      ["Can I use the sourced material with my own manufacturer?", "Potentially. The handover can identify the approved reference, supplier terms and open conditions, but purchasing, incoming inspection, testing, freight and manufacturer acceptance remain separate responsibilities unless included in writing."],
      ["When is the fabric ready for sampling or bulk purchase?", "A material can move to the agreed next stage after the required physical reference and supplier constraints are reviewed and the decision is recorded. Swatch approval does not automatically approve a garment sample, an unreviewed colour, a substitute or the later bulk lot."],
    ],
  },
  {
    slug: "fashion-production-management",
    keyword: "Fashion production management service",
    seoTitle: "Fashion Production Management Services",
    keywords: [
      "fashion production management",
      "apparel production management",
      "clothing production management",
      "fashion production coordination",
      "modest wear production management",
    ],
    eyebrow: "One Controlled Production Workflow",
    title: "Fashion Production Management from Sample to Shipment",
    titleAccent: "from Sample to Shipment",
    description: "Fashion production management for modest-wear brands: critical-path tracking, supplier coordination, approvals, quality checkpoints and shipment readiness.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/services/manufacturing-1.jpeg", "/images/26.jpeg"],
    contactValue: "Production Management",
    trustPoints: ["Written responsibility map", "Current critical path", "Documented approvals"],
    fit: "Modest-wear brands with approved designs or active samples that need clearer ownership across technical files, suppliers, materials, approvals, quality checkpoints and shipment preparation. Existing supplier relationships can be reviewed rather than automatically replaced.",
    timeline: "A project-specific critical path is prepared after the current files, sample stage, material status, approval owners, supplier capacity and required delivery window are reviewed. Open decisions or supplier changes can affect the schedule.",
    moq: "Production management has no separate manufacturing MOQ. Any garment, fabric, colour, embellishment, trim, packaging or supplier minimum is confirmed for the specific production route.",
    pricing: "Production-management support is quoted from the number of styles and suppliers, current development stage, reporting rhythm, approval workload, quality checkpoints, destination and engagement period. Scope is confirmed before payment.",
    quoteDescription: "Share the latest tech packs or specifications, sample status, suppliers, target quantities, materials, approval owners, required milestones, quality requirements and shipment destination. We will confirm the responsibilities, reporting route, exclusions, timing assumptions and fee in writing before payment.",
    deliverables: [
      "Current-file, sample and open-decision audit",
      "Written responsibility and communication map",
      "Project-specific critical path with dependencies",
      "Supplier question, approval and change log",
      "Production status, risk and escalation reporting",
      "Quality-checkpoint and shipment-readiness coordination",
    ],
    process: [
      "Share the latest files, sample status, suppliers, quantities and required milestones.",
      "We audit gaps and confirm responsibilities, reporting, timing assumptions, exclusions and pricing before payment.",
      "During the agreed engagement, we maintain the critical path, coordinate supplier questions and record approvals, changes and risks.",
      "The project closes with a documented status, approved references, available quality evidence, shipment-readiness checks and any open conditions.",
    ],
    resources: [
      ["When fashion production management is worth it", "/blog/production-management-fashion-brand"],
      ["Plan a fashion collection from brief to handover", "/blog/fashion-collection-development"],
      ["Understand garment sample stages", "/blog/types-of-garment-samples"],
      ["Prepare a design for a manufacturer", "/blog/prepare-design-for-manufacturer"],
      ["Review fashion tech pack services", "/services/fashion-tech-packs"],
      ["Review supply-chain and quality controls", "/supply-chain"],
      ["Understand project-specific production quotes", "/pricing#production-title"],
    ],
    faqs: [
      ["When should a brand use fashion production management?", "It is most useful when several styles, suppliers, sample stages or approval owners create dependencies that the brand cannot track reliably in one place. We review the current stage first so the proposal covers only the coordination that is actually needed."],
      ["Can you manage a factory or supplier I already use?", "Potentially. We first review the relationship, current files, sample history, communication route and the access needed to coordinate decisions. The written scope identifies what Zameett can manage and what remains with the brand or supplier."],
      ["What does a production status report include?", "The agreed report can show current milestones, completed approvals, pending decisions, material or sample dependencies, identified risks, responsible parties and the next required action. The reporting rhythm is confirmed in the proposal."],
      ["Does production management include manufacturing, inspection or freight?", "Not automatically. Management, manufacturing, materials, laboratory testing, independent inspection, freight and duties are separate responsibilities unless a specific item is included in the written scope."],
      ["Can you fix an incomplete tech pack during production management?", "We can identify missing or conflicting information and coordinate the questions. Creating or revising technical documentation is a separate service unless it is included in the proposal before payment."],
      ["How are production delays handled?", "Known risks are recorded against the critical path with an owner, impact and next decision. We can coordinate responses within the agreed scope, but supplier capacity, material availability, late approvals, changes and shipping conditions can still affect timing."],
      ["Do you guarantee a launch date?", "No. We prepare a realistic project-specific schedule after the files, materials, samples, approvals and supplier capacity are reviewed, then keep the dependencies visible as the project progresses."],
      ["How are pricing and manufacturing MOQ confirmed?", "The management fee follows the reviewed scope, styles, suppliers, reporting and engagement period. Manufacturing and material minimums remain project-specific and depend on the garment, fabric, colour, embellishment, trims, packaging and suppliers."],
    ],
  },];

export function getSolution(slug) {
  return SOLUTIONS.find((solution) => solution.slug === slug);
}
