export const SOLUTIONS = [
  {
    slug: "abaya-manufacturer-pakistan",
    keyword: "Abaya manufacturer in Pakistan",
    seoTitle: "Abaya Manufacturer in Pakistan for Modest Brands",
    eyebrow: "Specialist Abaya Production",
    title: "Abaya Manufacturer in Pakistan for Global Modest Brands",
    titleAccent: "for Global Modest Brands",
    description:
      "Specialist abaya design and manufacturing in Pakistan, from clean everyday silhouettes to layered, embroidered and embellished collections.",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "Abaya labels and designers who need accurate modest proportions, fabric-aware construction and reliable communication through sampling and production.",
    timeline: "Sampling and production timing is confirmed for the project after the design, materials, embellishment, quantity and supplier route are reviewed.",
    moq: "Manufacturing MOQ is project-specific and depends on the garment, fabric, colour, embellishment, trims, packaging, size mix and suppliers.",
    deliverables: ["Abaya design development and technical specifications", "Fabric and embellishment sourcing support", "Fit-sample route with agreed revisions", "Coordinated private-label production and quality checkpoints"],
    process: ["Send your sketches, references or collection mood board.", "We define silhouette, sizing, fabric and embellishment details.", "A sample is produced for fit and finish approval.", "Approved abayas move into production, QC and international delivery."],
    faqs: [
      ["What types of abayas can you manufacture?", "We support open and closed abayas, kaftan-inspired silhouettes, layered styles, bias cuts and embroidered or beaded statement pieces."],
      ["Can you source nida and other abaya fabrics?", "Yes. Fabric choices are proposed around opacity, drape, climate, finish and your target price point."],
      ["Do you offer custom sizing?", "Yes. We can work with your size chart or help develop one for your target market."],
      ["Can you add my brand labels?", "Yes. Woven labels, care labels, hangtags and packaging can be included in the production scope."],
    ],
  },
  {
    slug: "private-label-modest-clothing-manufacturer",
    keyword: "Private-label modest clothing manufacturer",
    seoTitle: "Private-Label Modest Clothing Manufacturer",
    eyebrow: "Your Label, Production Ready",
    title: "Private-Label Modest Clothing Manufacturing, End to End",
    titleAccent: "End to End",
    description:
      "Launch a branded modest collection with custom labels, packaging, sampling and production handled through one specialist team.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg", "/images/26.jpeg"],
    contactValue: "Custom Clothing Manufacturing (Private Label)",
    fit: "New and established brands that want original modest garments produced under their own name without building a fragmented supplier network.",
    timeline: "Development, sampling and production timing is quoted after style complexity, materials, branding, quantity and supplier availability are reviewed.",
    moq: "MOQ is confirmed per project. Garment, fabric, colour, trims, labels and packaging suppliers may each create separate minimums.",
    deliverables: ["Original garment development", "Custom woven and care labels", "Branded hangtags and packaging options", "Sampling, production, QC and export support"],
    process: ["Define your customer, price point and collection direction.", "Select designs, materials and branding components.", "Approve the garment sample and label placement.", "Approved production, inspection, packing and delivery handover are coordinated within the written scope."],
    faqs: [
      ["Is this white label or fully custom?", "Our private-label service is built around custom development. We can tailor the scope to your designs, branding and budget."],
      ["Can you help if I do not have tech packs?", "Yes. Tech-pack development can be included so the final product is properly documented before sampling."],
      ["Can packaging be customised?", "Yes. Depending on quantity, options can include branded bags, boxes, tissue, stickers, tags and insert cards."],
      ["Who owns the branding?", "Your brand name and supplied brand assets remain yours. Project-specific file ownership is confirmed in your written quote."],
    ],
  },
  {
    slug: "low-moq-clothing-manufacturer-pakistan",
    keyword: "Low MOQ clothing manufacturer Pakistan",
    seoTitle: "Low-MOQ Clothing Manufacturer in Pakistan",
    eyebrow: "Start Small, Scale Confidently",
    title: "Low-MOQ Modest-Wear Manufacturer in Pakistan for Emerging Brands",
    titleAccent: "for Emerging Brands",
    description:
      "Small-batch modest-wear manufacturing for emerging brands that need professional sampling, transparent quantity planning and a controlled path to scale.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/images/22.jpeg", "/images/27.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Founders testing a modest-wear capsule, boutique owners launching exclusives and designers who prefer controlled inventory over a large opening order.",
    timeline: "Sampling and production timing is quoted after the files, material availability, construction, target quantity and size-colour breakdown are confirmed.",
    moq: "MOQ is assessed per project. Garment, fabric, colour, embellishment, trims, packaging and supplier requirements determine the workable quantity.",
    deliverables: ["Feasibility and quantity planning", "Sample development before production", "Small-batch cutting and stitching", "Quality checks with a scale-up plan for reorders"],
    process: ["Tell us the styles, sizes, target units and launch date.", "We simplify materials or construction where it protects your budget.", "Approve a sample and final per-unit quote.", "Launch the small run, then reorder with the specifications already established."],
    faqs: [
      ["What is your exact minimum order?", "It varies by garment, fabric and customisation. Share the style and target quantity and we will give you a practical answer instead of a generic MOQ."],
      ["Can I mix sizes and colours?", "Usually yes, within material and cutting constraints. We confirm the workable breakdown in the quote."],
      ["Will low MOQ cost more per piece?", "Often, because setup and sourcing costs are spread across fewer units. We show the trade-off clearly and suggest ways to improve efficiency."],
      ["Can I scale the same style later?", "Yes. Once specifications and the approved sample are established, repeat production is faster and easier to plan."],
    ],
  },
  {
    slug: "abaya-tech-pack-designer",
    keyword: "Abaya tech pack designer",
    seoTitle: "Abaya Tech Pack Design Services for Fashion Brands",
    keywords: [
      "abaya tech pack designer",
      "abaya tech pack design",
      "modest fashion tech pack",
      "kaftan tech pack",
      "abaya technical drawing",
      "fashion tech pack services",
    ],
    eyebrow: "Technical Design for Modest Wear",
    title: "Abaya Tech Pack Design for Clearer Sampling and Production",
    titleAccent: "for Clearer Sampling and Production",
    description:
      "Specialist abaya tech pack design covering technical flats, construction, measurement specifications, materials, colourways and embellishment placement for sampling and supplier quotation.",
    cover: "/services/abaya-2.jpeg",
    gallery: ["/services/abaya-2.jpeg", "/services/abaya-1.jpeg", "/services/abaya-3.jpeg"],
    contactValue: "Fashion Tech Pack (Abaya / Kaftan / Modest Wear)",
    trustPoints: ["Abaya-specific scope", "Editable files where stated", "Packages from $95"],
    fit: "Abaya and modest-fashion brands that need the silhouette, coverage, drape, openings, sleeves and embellishment direction translated into clear technical documentation.",
    timeline:
      "Published one-style packages start from 3 business days for standard complexity. Layered, heavily embellished or multi-style projects receive a confirmed schedule before payment.",
    moq:
      "Tech-pack design is commissioned per style or collection. Any later sampling or manufacturing MOQ is separate and depends on the garment, fabric, colour, embellishment, trims and supplier requirements.",
    deliverables: [
      "Front, back and required detail technical flats",
      "Construction, opening, sleeve and finishing call-outs",
      "Fabric, lining, trim and complete bill of materials",
      "Measurement specifications within the agreed size scope",
      "Embroidery, beadwork, print or embellishment placement",
      "Colourways, revision references and agreed PDF or source files",
    ],
    process: [
      "Share your sketch, references, brand direction, target customer and any known measurements.",
      "Confirm the silhouette, opening, sleeves, layering, fabric, embellishment and file scope.",
      "Review the technical flats and specification through consolidated feedback.",
      "Receive the checked final pack for supplier quotation or sampling. Manufacturing is scoped separately.",
    ],
    faqs: [
      ["What do I need to provide?", "A sketch or visual references, the target customer, garment direction and any available size information are helpful. We clarify missing decisions before confirming the scope."],
      ["Can you document hand embroidery and beadwork?", "Yes. Placement, scale, artwork and application notes can be documented within the agreed scope. Physical testing and supplier execution remain separate stages."],
      ["Can you create measurement specifications?", "We can adapt an approved chart or prepare measurement specifications within the agreed size scope. This does not include a sewing pattern or standalone grading service."],
      ["Do you design kaftans and bisht styles too?", "Yes. Kaftans, bisht-inspired pieces and related modest silhouettes can be reviewed and scoped according to their construction and detailing."],
      ["Can you answer manufacturer questions?", "The included clarification support is stated in the selected package or proposal. New design changes outside the approved scope are quoted separately."],
      ["Are sampling and manufacturing included?", "No. The tech-pack package is a design and technical-documentation service. Sampling or modest-wear manufacturing can be reviewed separately, with project-specific MOQ and timing."],
    ],
  },
  {
    slug: "editable-fashion-tech-pack-template",
    keyword: "Editable fashion tech-pack template",
    seoTitle: "Editable Fashion Tech Pack Template Service",
    eyebrow: "Reusable Product-Development System",
    title: "Editable Fashion Tech-Pack Templates Made for Your Workflow",
    titleAccent: "Made for Your Workflow",
    description:
      "Customisable fashion tech-pack templates with clear pages for flats, measurements, BOMs, colourways, artwork and revision tracking.",
    cover: "/digital/p1-1.jpeg",
    gallery: ["/digital/p1-1.jpeg", "/digital/p1-2.jpeg", "/digital/p1-3.jpeg"],
    contactValue: "Design & Tech Packs Only",
    fit: "In-house designers, fashion students and growing labels that want a repeatable, editable structure for future product development.",
    timeline: "A customised template is typically prepared within 3 to 7 business days after your format, branding and category needs are confirmed.",
    moq: "Purchase or commission one reusable template and duplicate it for future styles according to the included licence.",
    deliverables: ["Editable, brand-ready page system", "Measurement and bill-of-material tables", "Colourway, artwork and label sections", "Revision log plus PDF export layout"],
    process: ["Choose your garment category and preferred software.", "Share your logo, colours and existing factory requirements.", "Review the page structure and sample style.", "Receive the editable master template and usage guidance."],
    faqs: [
      ["Which editable formats are available?", "Available formats depend on the template or custom scope. Tell us your software before ordering so compatibility is confirmed."],
      ["Is this a completed tech pack?", "A template is the reusable framework. If you need a finished pack for a specific garment, choose our tech-pack design service."],
      ["Can you add my logo and brand colours?", "Yes. Custom branding and additional category-specific pages can be included."],
      ["Can my team reuse it?", "Yes, subject to the licence provided with the product. We can also quote a team-specific custom template."],
    ],
  },
  {
    slug: "fashion-sampling-services",
    keyword: "Garment sampling and fitting service",
    seoTitle: "Garment Sampling & Fitting Services",
    eyebrow: "Approve Before You Produce",
    title: "Garment Sampling and Fitting for Modest Fashion Brands",
    titleAccent: "for Modest Fashion Brands",
    description: "Prototype development, fit review and documented corrections for modest-fashion collections before bulk production.",
    cover: "/services/manufacturing-2.jpeg",
    gallery: ["/services/manufacturing-2.jpeg", "/images/18.jpeg", "/images/23.jpeg"],
    contactValue: "Sampling & Production",
    fit: "Brands with designs or tech packs ready that need a physical prototype, specialist fit review and a controlled revision round.",
    timeline: "The sampling schedule is confirmed after specifications, materials, construction complexity and the review route are approved.",
    moq: "A single development sample can be reviewed before deciding whether to continue into a broader sampling or production scope.",
    deliverables: ["Prototype in approved development materials", "Measurement and fit review", "Construction, finish and modesty checks", "Consolidated sample comments"],
    process: ["Share the latest tech pack or design brief.", "Confirm materials, measurements and review criteria.", "Assess the prototype through one organised correction record.", "Approve the sample or begin a scoped revision round."],
    faqs: [
      ["Can you sample a tech pack made by another designer?", "Yes. We first audit it for missing measurements, materials or construction decisions."],
      ["Do you fit-test modest garments differently?", "Yes. We review movement, opacity, length, sleeve reach, opening coverage and layering."],
      ["Is the sample made in final fabric?", "Where practical, yes. Any development substitute is proposed and disclosed before sampling."],
      ["Can you manage revisions with my factory?", "Technical revision support can be scoped when the factory follows one controlled comment and tech-pack process."],
    ],
  },
  {
    slug: "fabric-sourcing-modest-fashion",
    keyword: "Fabric sourcing for modest fashion",
    seoTitle: "Fabric Sourcing for Modest Fashion Brands",
    eyebrow: "Material Decisions Made Clear",
    title: "Fabric Sourcing for Abayas and Modest-Wear Collections",
    titleAccent: "for Abayas and Modest-Wear Collections",
    description: "Fabric and trim sourcing guided by opacity, drape, climate, care, embellishment, target price and quantity.",
    cover: "/images/25.jpeg",
    gallery: ["/images/25.jpeg", "/images/24.jpeg", "/services/textile-2.jpeg"],
    contactValue: "Fabric & Trim Sourcing",
    fit: "Labels that know the silhouette but need commercially suitable fabric, lining, trims or embellishment bases before sampling.",
    timeline: "The sourcing schedule is confirmed after material requirements, colour, quantity, destination and supplier response times are reviewed.",
    moq: "Minimums vary by quality, colour and finish. Stock materials offer the most flexibility; custom dyeing and printing require more quantity.",
    deliverables: ["Shortlisted material options", "Composition and use guidance", "Supplier MOQ and lead-time information", "Swatch coordination where included"],
    process: ["Define use, target price, colour and performance.", "Review practical stock or custom routes.", "Check swatches, opacity, drape and construction compatibility.", "Approve the quality reference before purchasing."],
    faqs: [
      ["Can you source common abaya fabrics?", "Yes. The recommendation follows drape, opacity, climate, care and price rather than the fabric name alone."],
      ["Can you guarantee an exact screen colour?", "No. Final colour should be approved on a physical swatch or strike-off."],
      ["Do fabric suppliers have separate MOQs?", "Usually. We disclose the relevant roll, metre, colour or print minimum before approval."],
      ["Can I use the fabric with my own manufacturer?", "Yes when the agreed sourcing scope supports a direct handoff."],
    ],
  },
  {
    slug: "fashion-production-management",
    keyword: "Fashion production management service",
    seoTitle: "Fashion Production Management Services",
    eyebrow: "One Controlled Production Workflow",
    title: "Fashion Production Management from Sample to Shipment",
    titleAccent: "from Sample to Shipment",
    description: "Milestone, supplier, approval and quality-control coordination for modest-fashion brands that need an accountable workflow.",
    cover: "/services/manufacturing-3.jpeg",
    gallery: ["/services/manufacturing-3.jpeg", "/services/manufacturing-1.jpeg", "/images/26.jpeg"],
    contactValue: "Production Management",
    fit: "Growing labels with several styles, suppliers or approval stages that need clearer timelines and one documented source of truth.",
    timeline: "The schedule follows the approved critical path and depends on sampling, material lead time, quantity and supplier capacity.",
    moq: "Management has no universal MOQ, but manufacturers and material suppliers may each have minimums.",
    deliverables: ["Critical path and milestone tracking", "Supplier and approval coordination", "Purchase-order and specification checks", "Quality and shipment readiness"],
    process: ["Audit files, samples and open decisions.", "Build responsibilities and the critical path.", "Track approvals, risks and updates.", "Close production with inspection and shipment handover."],
    faqs: [
      ["Can you manage a factory I already use?", "Potentially, after reviewing the relationship, files, history and access required."],
      ["Does management include manufacturing cost?", "No. Management, manufacturing, materials, testing and freight are separated in the proposal."],
      ["How are delays handled?", "Risks are logged against the critical path with an owner and next decision."],
      ["Do you guarantee a launch date?", "We provide a realistic schedule after materials, samples and capacity are confirmed."],
    ],
  },];

export function getSolution(slug) {
  return SOLUTIONS.find((solution) => solution.slug === slug);
}
