export const FAQS = [
  { q: "Can I commission design work without manufacturing?", a: "Yes. Zameett can provide fashion concepts, technical flats, tech packs, textile prints, measurement specification charts and other agreed development files without a manufacturing commitment. Sewing patterns and pattern grading are not currently offered. Exact deliverables and file formats are confirmed in the proposal." },
  { q: "What is a tech pack and why is it useful?", a: "A tech pack records the drawings, measurements, construction details, materials, artwork and revision information agreed for a garment. It gives the sample maker or manufacturer a clearer production reference and reduces avoidable interpretation." },
  { q: "Can you review an existing garment or failed sample?", a: "Yes. We can review the available files, photos and feedback, identify documentation gaps and propose a clearly scoped correction route. The recommendation depends on what evidence and physical samples are available." },
  { q: "Which apparel categories do you support?", a: "Design and technical-development services are available across womenswear, menswear, childrenswear, streetwear, activewear, dresses, outerwear and modest fashion. Our core sampling and production specialisation is modest wear; other production categories are considered after project review." },
  { q: "What is your minimum order quantity?", a: "Flexible MOQs may be available. The final minimum depends on the garment, fabric, colour, embellishment, trim, packaging and supplier requirements, and is confirmed for the specific project." },
  { q: "Do you arrange international delivery?", a: "International delivery options can be discussed. The available courier or freight method, charges, customs responsibility, destination restrictions and delivery estimate are confirmed for the project before dispatch." },
  { q: "How long does development or production take?", a: "The timeline depends on style count, complexity, material availability, feedback speed, sampling rounds, quantity and capacity. The quotation provides an estimate, and dates are reconfirmed after required approvals and payments." },
  { q: "How do I get started?", a: "Complete the quote form with your category, style count, quantity, target market and preferred delivery date. You can upload small reference files or provide a Drive or WeTransfer link. We aim to respond within one business day." },
];
