// Featured service pages. Service values must match the enquiry form.
export const GIGS = [
  {
    slug: "fashion-tech-packs",
    title: "Fashion Tech Pack Services & Technical Design",
    short: "Fashion Tech Packs",
    tagline: "Professional fashion design and production-ready tech packs for clothing brands preparing to sample, quote or manufacture.",
    serviceValue: "Fashion Tech Pack & Technical Design",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    intro: [
      "Modest garments often require specialist attention to proportion, drape, layering and embellishment placement. Our tech packs document these decisions clearly so your manufacturer has an accurate production reference.",
      "Technical-design support is also available for womenswear, menswear, childrenswear, streetwear, activewear, dresses and outerwear. Scope and deliverable formats are confirmed in the proposal for each project.",
      "Send a sketch, reference images or an existing specification and we will define the pages, measurements and source formats required before work begins.",
    ],
    listTitle: "A project may include",
    list: [
      "Front, back and detail technical flats",
      "Construction, seam and finish call-outs",
      "Bill of materials and trim references",
      "Colour, artwork and placement specifications",
      "Measurement specification charts, points of measurement and technical sizing documentation where scoped",
      "Revision date and approval reference",
      "Exact source and export formats stated in your proposal",
    ],
    whyTitle: "Specialist documentation",
    why: [
      "Proportion, coverage and layering decisions",
      "Drape, opening and closure construction",
      "Embroidery, print and embellishment placement",
      "A controlled reference for sampling and quotation",
    ],
    note: "Final pages, revision rounds, source files and export formats are confirmed before the project starts. A tech pack reduces ambiguity but does not replace professional pattern development, sampling, competent manufacturing or physical fit approval.",
  },
  {
    slug: "custom-textile-patterns",
    title: "Custom Textile Prints & Placement Artwork",
    short: "Custom Textile Patterns",
    tagline: "Original repeat patterns, placements and colourways prepared for fashion-product development.",
    serviceValue: "Custom Textile Patterns & Artwork",
    cover: "/services/textile-1.jpeg",
    gallery: ["/services/textile-1.jpeg", "/services/textile-2.jpeg", "/services/textile-3.jpeg"],
    pdf: "/services/textile-prints-portfolio.pdf",
    intro: [
      "We create original textile artwork around your brand direction, garment category and intended print method.",
      "Repeat type, scale, colourways, placement and final file formats are agreed before delivery so the artwork is prepared for the intended supplier workflow.",
    ],
    listTitle: "Available deliverables",
    list: [
      "Seamless repeat patterns",
      "Placement artwork for defined garment panels",
      "Approved colourway variations",
      "Scale and repeat references",
      "Layered source files where included in the proposal",
    ],
    whyTitle: "A controlled artwork process",
    why: [
      "Brand-led concept development",
      "Print-scale and colour review",
      "Organised revisions and approval files",
    ],
    note: "Printing method, colour limitations, fabric and supplier requirements should be confirmed before production testing.",
  },
  {
    slug: "clothing-manufacturing",
    title: "Modest Wear Product Development & Manufacturing",
    short: "Modest Wear Development",
    tagline: "Specialist design, technical development, sampling and project-specific manufacturing support for abayas, kaftans, modest dresses and coordinated collections.",
    serviceValue: "Modest-Wear Sampling & Manufacturing",
    cover: "/services/manufacturing-1.jpeg",
    gallery: ["/services/manufacturing-1.jpeg", "/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg"],
    intro: [
      "Zameett helps modest-fashion brands move from an early idea or existing design into a clearly documented, sample-reviewed product. The route can include concept refinement, technical documentation, textile artwork, material sourcing, sampling and production coordination, depending on the brief.",
      "Our design and technical-development services support apparel categories beyond modest wear. Sampling and manufacturing specialisation is primarily abayas, kaftans, modest dresses, scarves, layering pieces and coordinated modest collections; every physical-production enquiry is reviewed for capability and fit.",
      "Manufacturing MOQ is project-specific. Garment construction, fabric, colour split, embellishment, trims, packaging and supplier requirements all affect the workable quantity, quotation and schedule.",
    ],
    listTitle: "Production support may include",
    list: [
      "Scope, quantity and supplier-capability review",
      "Fabric, trim and private-label sourcing",
      "Prototype and pre-production sample development",
      "Written sample corrections and approval records",
      "Bulk production after written sample and specification approval",
      "Documented quality checkpoints before dispatch",
      "Shipping options confirmed for the product and destination",
    ],
    whyTitle: "Controlled before bulk",
    why: [
      "Product-specific MOQ confirmation",
      "Material and embellishment approval",
      "Sample review before bulk cutting",
      "Clear production and dispatch checkpoints",
    ],
    note: "Scope, deliverables, revisions, MOQ, capacity, timeline, payment terms, shipping assumptions and exclusions are confirmed in writing before payment. Bulk production proceeds only after the required sample and specification approvals.",
  },
];

export function getGig(slug) {
  return GIGS.find((gig) => gig.slug === slug);
}
