// Featured service pages. Service values must match the enquiry form.
export const GIGS = [
  {
    slug: "fashion-tech-packs",
    title: "Fashion Tech Pack Services & Technical Design",
    short: "Fashion Tech Packs",
    tagline: "Professional fashion design and production-ready tech packs for clothing brands preparing to sample, quote or manufacture.",
    serviceValue: "Fashion Tech Pack & Technical Design",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    intro: [
      "Modest garments often require specialist attention to proportion, drape, layering and embellishment placement. Our tech packs document these decisions clearly so your manufacturer has an accurate production reference.",
      "Technical-design support is also available for womenswear, menswear, childrenswear, streetwear, activewear, dresses and outerwear. Scope and deliverable formats are confirmed in the proposal for each project.",
      "Send a sketch, reference images or an existing specification and we will define the pages, measurements and source formats required before work begins.",
    ],
    listTitle: "A project may include",
    list: [
      "Front, back and detail technical flats",
      "Construction, seam and finish call-outs",
      "Bill of materials and trim references",
      "Colour, artwork and placement specifications",
      "Measurement specification charts, points of measurement and technical sizing documentation where scoped",
      "Revision date and approval reference",
      "Exact source and export formats stated in your proposal",
    ],
    whyTitle: "Specialist documentation",
    why: [
      "Proportion, coverage and layering decisions",
      "Drape, opening and closure construction",
      "Embroidery, print and embellishment placement",
      "A controlled reference for sampling and quotation",
    ],
    note: "Final pages, revision rounds, source files and export formats are confirmed before the project starts. A tech pack reduces ambiguity but does not replace professional pattern development, sampling, competent manufacturing or physical fit approval.",
  },
  {
    slug: "custom-textile-patterns",
    title: "Custom Textile Pattern Design & Placement Prints",
    short: "Custom Textile Patterns",
    tagline: "Original seamless repeats, placement prints and colourways developed for apparel brands and prepared around the intended supplier workflow.",
    serviceValue: "Custom Textile Patterns & Artwork",
    cover: "/services/textile-1.jpeg",
    gallery: ["/services/textile-1.jpeg", "/services/textile-2.jpeg", "/services/textile-3.jpeg"],
    pdf: "/services/textile-prints-portfolio.pdf",
    intro: [
      "Zameett develops original textile artwork around your brand direction, garment category, fabric, physical scale and intended print method. The service is suitable when you need artwork created for a defined fashion product rather than a generic stock pattern.",
      "Projects can cover a seamless repeat for yardage, a placement or engineered print for a defined panel, coordinated scarf artwork, or colourways for a collection. The exact artwork route is agreed before concept development begins.",
      "Repeat type, scale, colour references, placement dimensions, revision rounds and final file formats are confirmed in writing before payment. Physical fabric printing, strike-offs and supplier production testing are separate unless explicitly included.",
    ],
    listTitle: "Available deliverables",
    list: [
      "Seamless repeat patterns",
      "Placement artwork for defined garment panels",
      "Approved colourway variations",
      "Physical scale, repeat-tile or placement references",
      "Artwork notes for the agreed printer handoff",
      "Layered source files where included in the proposal",
    ],
    whyTitle: "A controlled artwork process",
    why: [
      "Brand-led concept development",
      "Print-scale and colour review",
      "Organised revisions and approval files",
      "Supplier requirements checked before final export",
    ],
    note: "Scope must be confirmed before payment. Screen, digital, sublimation and other print workflows can require different colour, repeat, resolution and file settings, so the final production export should follow the selected supplier's current specification and be validated through an appropriate physical test.",
  },
  {
    slug: "clothing-manufacturing",
    title: "Modest Wear Product Development & Manufacturing",
    short: "Modest Wear Development",
    tagline: "Specialist design, technical development, sampling and project-specific manufacturing support for abayas, kaftans, modest dresses and coordinated collections.",
    serviceValue: "Modest-Wear Sampling & Manufacturing",
    cover: "/services/manufacturing-1.jpeg",
    gallery: ["/services/manufacturing-1.jpeg", "/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg"],
    intro: [
      "Zameett helps modest-fashion brands move from an early idea or existing design into a clearly documented, sample-reviewed product. The route can include concept refinement, technical documentation, textile artwork, material sourcing, sampling and production coordination, depending on the brief.",
      "Our design and technical-development services support apparel categories beyond modest wear. Sampling and manufacturing specialisation is primarily abayas, kaftans, modest dresses, scarves, layering pieces and coordinated modest collections; every physical-production enquiry is reviewed for capability and fit.",
      "Manufacturing MOQ is project-specific. Garment construction, fabric, colour split, embellishment, trims, packaging and supplier requirements all affect the workable quantity, quotation and schedule.",
    ],
    listTitle: "Production support may include",
    list: [
      "Scope, quantity and supplier-capability review",
      "Fabric, trim and private-label sourcing",
      "Prototype and pre-production sample development",
      "Written sample corrections and approval records",
      "Bulk production after written sample and specification approval",
      "Documented quality checkpoints before dispatch",
      "Shipping options confirmed for the product and destination",
    ],
    whyTitle: "Controlled before bulk",
    why: [
      "Product-specific MOQ confirmation",
      "Material and embellishment approval",
      "Sample review before bulk cutting",
      "Clear production and dispatch checkpoints",
    ],
    note: "Scope, deliverables, revisions, MOQ, capacity, timeline, payment terms, shipping assumptions and exclusions are confirmed in writing before payment. Bulk production proceeds only after the required sample and specification approvals.",
  },
];

export function getGig(slug) {
  return GIGS.find((gig) => gig.slug === slug);
}
