// Featured service pages. Service values must match the enquiry form.
export const GIGS = [
  {
    slug: "fashion-tech-packs",
    title: "Fashion Tech Packs & Technical Design",
    short: "Fashion Tech Packs",
    tagline: "Clear, production-ready technical documentation for modest wear and wider apparel categories.",
    serviceValue: "Fashion Tech Pack & Technical Design",
    cover: "/services/abaya-1.jpeg",
    gallery: ["/services/abaya-1.jpeg", "/services/abaya-2.jpeg", "/services/abaya-3.jpeg"],
    intro: [
      "Modest garments often require specialist attention to proportion, drape, layering and embellishment placement. Our tech packs document these decisions clearly so your manufacturer has an accurate production reference.",
      "Technical-design support is also available for womenswear, menswear, childrenswear, streetwear, activewear, dresses and outerwear. Scope and deliverable formats are confirmed in the proposal for each project.",
      "Send a sketch, reference images or an existing specification and we will define the pages, measurements and source formats required before work begins.",
    ],
    listTitle: "A project may include",
    list: [
      "Front, back and detail technical flats",
      "Construction, seam and finish call-outs",
      "Bill of materials and trim references",
      "Colour, artwork and placement specifications",
      "Measurement specification charts, points of measurement and technical sizing documentation where scoped",
      "Revision date and approval reference",
      "Exact source and export formats stated in your proposal",
    ],
    whyTitle: "Specialist documentation",
    why: [
      "Proportion, coverage and layering decisions",
      "Drape, opening and closure construction",
      "Embroidery, print and embellishment placement",
      "A controlled reference for sampling and quotation",
    ],
    note: "Final pages, revision rounds, source files and export formats are confirmed before the project starts. A tech pack reduces ambiguity but does not replace professional pattern development, sampling, competent manufacturing or physical fit approval.",
  },
  {
    slug: "custom-textile-patterns",
    title: "Custom Textile Prints & Placement Artwork",
    short: "Custom Textile Patterns",
    tagline: "Original repeat patterns, placements and colourways prepared for fashion-product development.",
    serviceValue: "Custom Textile Patterns & Artwork",
    cover: "/services/textile-1.jpeg",
    gallery: ["/services/textile-1.jpeg", "/services/textile-2.jpeg", "/services/textile-3.jpeg"],
    pdf: "/services/textile-prints-portfolio.pdf",
    intro: [
      "We create original textile artwork around your brand direction, garment category and intended print method.",
      "Repeat type, scale, colourways, placement and final file formats are agreed before delivery so the artwork is prepared for the intended supplier workflow.",
    ],
    listTitle: "Available deliverables",
    list: [
      "Seamless repeat patterns",
      "Placement artwork for defined garment panels",
      "Approved colourway variations",
      "Scale and repeat references",
      "Layered source files where included in the proposal",
    ],
    whyTitle: "A controlled artwork process",
    why: [
      "Brand-led concept development",
      "Print-scale and colour review",
      "Organised revisions and approval files",
    ],
    note: "Printing method, colour limitations, fabric and supplier requirements should be confirmed before production testing.",
  },
  {
    slug: "clothing-manufacturing",
    title: "Modest-Wear Sampling & Manufacturing",
    short: "Modest-Wear Manufacturing",
    tagline: "Reviewed sampling and production support for abayas, kaftans, modest dresses and coordinated collections.",
    serviceValue: "Modest-Wear Sampling & Manufacturing",
    cover: "/services/manufacturing-1.jpeg",
    gallery: ["/services/manufacturing-1.jpeg", "/services/manufacturing-2.jpeg", "/services/manufacturing-3.jpeg"],
    intro: [
      "Zameett specialises in modest-wear sampling and manufacturing, including abayas, kaftans, modest dresses, scarves and coordinated collections. For other apparel categories, we provide fashion design, technical flats, tech packs, textile print design and product-development support.",
      "Our fashion design, technical design and tech-pack services are available for a broad range of apparel categories. Other sampling or production categories may be considered after a capability, quantity and timeline review.",
      "Flexible MOQs are available. Final minimum quantity depends on the garment, fabric, colour, embellishment and supplier requirements.",
    ],
    listTitle: "Production support may include",
    list: [
      "Scope, quantity and supplier-capability review",
      "Fabric, trim and private-label sourcing",
      "Prototype and pre-production sample development",
      "Written sample corrections and approval records",
      "Bulk production after written sample and specification approval",
      "Documented quality checkpoints before dispatch",
      "Shipping options confirmed for the product and destination",
    ],
    whyTitle: "Controlled before bulk",
    why: [
      "Product-specific MOQ confirmation",
      "Material and embellishment approval",
      "Sample review before bulk cutting",
      "Clear production and dispatch checkpoints",
    ],
    note: "MOQ, capacity, lead time, shipping, duties and delivery options are confirmed for each product and destination before an order is accepted.",
  },
];

export function getGig(slug) {
  return GIGS.find((gig) => gig.slug === slug);
}
