const COMMON_SPECS = {
  formats: "Adobe Illustrator (.AI) editable source and PDF reference/export",
  illustrator: "Required for full source-file editing",
  canva: "Not included",
  spreadsheets: "Excel and Google Sheets versions are not included",
  pageSize: "Document layouts are supplied in the included source file; confirm print settings before export",
  fonts: "Font files and paid font licences are not included",
  instructions: "Page labels and editable placeholders are included; software training is not included",
  sampleData: "Illustrative placeholders only. These are not approved production measurements",
  licence: "Single-brand commercial-use licence; resale or redistribution of the template is prohibited",
  updates: "Future updates are not included unless stated in the order",
  support: "Seven days of delivery/access support; customisation and technical design are separate services",
  excluded: "Custom garment design, validated measurements, grading rules, sewing pattern, fit testing and factory approval",
};

export const PRODUCTS = [
  {
    slug: "tech-pack-template-pro",
    name: "Tech Pack Template: Pro Edition",
    short: "Tech Pack Template: Pro",
    tagline: "An editable technical-document layout with dedicated sections for drawings, materials, measurements and construction notes.",
    price: "$22", priceCents: 2200, badge: "Most Complete",
    cover: "/digital/p2-1.jpeg", gallery: ["/digital/p2-1.jpeg", "/digital/p2-2.jpeg", "/digital/p2-3.jpeg"],
    intro: ["A structured starting point for organising garment-development information in Adobe Illustrator.", "Replace all sample placeholders with project-specific technical information and have measurements, patterns and construction decisions reviewed by qualified professionals before production."],
    listTitle: "Seven core page layouts",
    list: ["Front, back and detail drawing layouts", "Bill of Materials layout", "Measurement / POM and technical sizing layout", "Colourway layout", "Fabric and trim reference layout", "Construction-note layout", "Revision and identification fields"],
    specs: { ...COMMON_SPECS, pages: "Seven core page layouts" },
    note: "The template contains editable measurement and technical sizing layouts; it does not create accurate garment measurements, sewing patterns, grading rules or fit approval.",
  },
  {
    slug: "tech-pack-template-classic",
    name: "Tech Pack Template: Classic Edition",
    short: "Tech Pack Template: Classic",
    tagline: "A clean editable layout for organising the core information used during garment development.",
    price: "$14", priceCents: 1400,
    cover: "/digital/p1-1.jpeg", gallery: ["/digital/p1-1.jpeg", "/digital/p1-2.jpeg", "/digital/p1-3.jpeg"],
    intro: ["A six-layout starting point for brands that want organised technical documentation in Adobe Illustrator.", "All placeholder content must be replaced and professionally checked for the specific garment before sampling or production."],
    listTitle: "Six core page layouts",
    list: ["Technical drawing layout", "Fabric reference layout", "Colourway layout", "Measurement / POM layout", "Bill of Materials layout", "Construction and identification fields"],
    specs: { ...COMMON_SPECS, pages: "Six core page layouts" },
    note: "The template contains editable measurement and technical sizing layouts; it does not create accurate garment measurements, sewing patterns, grading rules or fit approval.",
  },
  {
    slug: "tech-pack-template-blush",
    name: "Tech Pack Template: Blush Edition",
    short: "Tech Pack Template: Blush",
    tagline: "An editable six-layout technical-document template with a refined blush visual system.",
    price: "$14", priceCents: 1400,
    cover: "/digital/p3-1.jpeg", gallery: ["/digital/p3-1.jpeg", "/digital/p3-2.jpeg", "/digital/p3-3.jpeg"],
    intro: ["A styled Adobe Illustrator starting point for organising drawing, material, colourway and measurement information.", "The visual template does not validate garment engineering; replace every placeholder and obtain professional technical review before production."],
    listTitle: "Six core page layouts",
    list: ["Front and back drawing layout", "Fabric reference layout", "Colourway layout", "Measurement / POM layout", "Bill of Materials layout", "Construction and identification fields"],
    specs: { ...COMMON_SPECS, pages: "Six core page layouts" },
    note: "The template contains editable measurement and technical sizing layouts; it does not create accurate garment measurements, sewing patterns, grading rules or fit approval.",
  },
];

export function getProduct(slug) { return PRODUCTS.find((product) => product.slug === slug); }
