import { SEO_POSTS } from "./seo-posts.js";

const LEGACY_POSTS = [
  {
    slug: "abaya-manufacturing-cost",
    title: "How Much Does It Cost to Manufacture an Abaya?",
    titleAccent: "Manufacture an Abaya?",
    description: "A practical cost breakdown covering fabric, construction, embellishment, sampling, labels, quantity and freight. It also includes a worked costing example.",
    primaryKeyword: "abaya manufacturing cost",
    date: "2026-07-13",
    image: "/services/manufacturing-1.jpeg",
    readTime: "9 min read",
  },
  {
    slug: "complete-abaya-manufacturing-process",
    title: "The Complete Abaya Manufacturing Process",
    titleAccent: "Abaya Manufacturing Process",
    description: "From design brief and tech pack to fabric approval, sampling, cutting, stitching, finishing, quality control and shipment.",
    primaryKeyword: "abaya manufacturing process",
    date: "2026-07-06",
    image: "/services/manufacturing-2.jpeg",
    readTime: "10 min read",
  },
  {
    slug: "how-to-create-a-tech-pack-for-abayas",
    title: "What Should an Abaya Tech Pack Include?",
    titleAccent: "Abaya Tech Pack Include?",
    description: "The exact drawings, measurements, construction notes, BOM, artwork and revision controls a factory needs to sample an abaya accurately.",
    primaryKeyword: "abaya tech pack",
    date: "2026-06-29",
    image: "/images/14.jpeg",
    readTime: "11 min read",
  },
  {
    slug: "modest-fashion-manufacturer-pakistan",
    title: "How to Find a Modest-Fashion Manufacturer",
    titleAccent: "Modest-Fashion Manufacturer",
    description: "A due-diligence guide for comparing specialisation, samples, MOQs, quality systems, communication and production claims before paying a deposit.",
    primaryKeyword: "how to find a modest fashion manufacturer",
    date: "2026-06-22",
    image: "/images/27.jpeg",
    readTime: "9 min read",
  },
  {
    slug: "low-moq-vs-bulk-fashion-manufacturing",
    title: "Low MOQ vs Bulk Clothing Manufacturing",
    titleAccent: "Bulk Clothing Manufacturing",
    description: "Compare low-MOQ and bulk clothing production across unit cost, cash exposure, SKU depth, demand evidence, reorders and supplier constraints.",
    primaryKeyword: "low MOQ vs bulk manufacturing",
    date: "2026-06-15",
    updatedDate: "2026-09-10",
    image: "/services/manufacturing-3.jpeg",
    readTime: "12 min read",
    serviceHref: "/services/clothing-manufacturing",
    serviceLabel: "Project-specific modest-wear production support",
    related: ["abaya-manufacturer-moq", "private-label-vs-custom-manufacturing", "how-to-start-a-modest-fashion-brand"],
  },
  {
    slug: "fabric-guide-abayas-modest-dresses",
    title: "Fabric Guide for Abayas and Modest Dresses",
    titleAccent: "Abayas and Modest Dresses",
    description: "Compare abaya fabrics by drape, opacity, structure, care and construction, then use a controlled sample and testing route before bulk approval.",
    primaryKeyword: "best fabric for abayas",
    date: "2026-06-08",
    image: "/images/25.jpeg",
    readTime: "16 min read",
    updatedDate: "2026-09-26",
    serviceHref: "/services/clothing-manufacturing",
    serviceLabel: "Modest-wear development and manufacturing support",
    related: ["fabric-sourcing-checklist-fashion-brand", "types-of-garment-samples", "abaya-manufacturer-moq"],
  },
  {
    slug: "tech-pack-mistakes-delay-production",
    title: "Tech-Pack Mistakes That Delay Production",
    titleAccent: "Delay Production",
    description: "Diagnose common tech-pack mistakes that cause factory questions, failed samples and revisions, then use a controlled prevention and correction workflow.",
    primaryKeyword: "tech pack mistakes",
    date: "2026-06-01",
    image: "/images/techpack.jpeg",
    readTime: "12 min read",
    updatedDate: "2026-09-06",
    serviceHref: "/services/fashion-tech-packs",
    serviceLabel: "Production-ready tech pack services",
    related: ["what-is-a-tech-pack", "tech-pack-example", "bill-of-materials-fashion"],
  },
  {
    slug: "how-to-start-a-modest-fashion-brand",
    title: "How to Start a Modest-Clothing Brand",
    titleAccent: "Modest-Clothing Brand",
    description: "Start a modest-clothing brand with customer evidence, a controlled first collection, production-ready files, sampling gates and a measurable launch plan.",
    primaryKeyword: "how to start a modest clothing brand",
    date: "2026-05-25",
    image: "/images/19.jpeg",
    readTime: "14 min read",
    updatedDate: "2026-09-08",
    serviceHref: "/services/clothing-manufacturing",
    serviceLabel: "Modest-wear development and manufacturing",
    related: ["fabric-guide-abayas-modest-dresses", "types-of-garment-samples", "private-label-vs-custom-manufacturing"],
  },
  {
    slug: "private-label-vs-custom-manufacturing",
    title: "Private Label vs Custom Clothing Manufacturing",
    titleAccent: "Custom Clothing Manufacturing",
    description: "Compare private-label and custom clothing manufacturing across product control, development, MOQ, costing, approvals and supplier questions.",
    primaryKeyword: "private label vs custom manufacturing",
    date: "2026-07-20",
    updatedDate: "2026-09-09",
    image: "/services/manufacturing-2.jpeg",
    readTime: "12 min read",
    serviceHref: "/services/clothing-manufacturing",
    serviceLabel: "Modest-wear development and manufacturing",
    related: ["how-to-start-a-modest-fashion-brand", "prepare-design-for-manufacturer", "low-moq-vs-bulk-fashion-manufacturing"],
  },
  {
    slug: "garment-sampling-process-modest-fashion",
    title: "The Garment Sampling Process for Modest Fashion",
    titleAccent: "for Modest Fashion",
    description: "A practical guide to prototype, fit, size-set and pre-production samples with modest-wear approval checkpoints.",
    date: "2026-07-19",
    image: "/images/23.jpeg",
    readTime: "9 min read",
  },
  {
    slug: "fabric-sourcing-checklist-fashion-brand",
    title: "Fabric Sourcing Checklist for Fashion Brands",
    titleAccent: "for Fashion Brands",
    description: "Use this fabric sourcing checklist to confirm composition, opacity, drape, width, shrinkage, colour, MOQ and lead time before ordering.",
    primaryKeyword: "fabric sourcing checklist",
    date: "2026-07-18",
    updatedDate: "2026-09-06",
    image: "/images/25.jpeg",
    readTime: "10 min read",
    serviceHref: "/supply-chain",
    serviceLabel: "Fabric sourcing and quality support",
    related: ["fabric-guide-abayas-modest-dresses", "prepare-design-for-manufacturer", "production-management-fashion-brand"],
  },
  {
    slug: "production-management-fashion-brand",
    title: "Fashion Production Management: When Does a Brand Need It?",
    titleAccent: "When Does a Brand Need It?",
    description: "Decide when fashion production management is worthwhile, what it should control, which approval gates matter and how to scope support clearly.",
    primaryKeyword: "fashion production management",
    date: "2026-07-17",
    updatedDate: "2026-09-09",
    image: "/services/manufacturing-3.jpeg",
    readTime: "12 min read",
    serviceHref: "/solutions/fashion-production-management",
    serviceLabel: "Fashion production management support",
    related: ["fashion-collection-development", "types-of-garment-samples", "fabric-sourcing-checklist-fashion-brand"],
  },];

const BLOG_IMAGE_OVERRIDES = {
  "tech-pack-cost": { image: "/images/01.jpeg", imageAlt: "Fashion technical documents arranged for a tech pack costing review" },
  "tech-pack-example": { image: "/images/02.jpeg", imageAlt: "Fashion specification pages illustrating a production-ready tech pack" },
  "fashion-technical-flat-drawings": { image: "/images/03.jpeg", imageAlt: "Detailed fashion technical drawings prepared for garment development" },
  "what-is-a-tech-pack": { image: "/images/04.jpeg", imageAlt: "Fashion design documents introducing the structure of a clothing tech pack" },
  "tech-pack-vs-spec-sheet-pattern": { image: "/images/05.jpeg", imageAlt: "Technical garment documentation used to compare production file types" },
  "bill-of-materials-fashion": { image: "/images/06.jpeg", imageAlt: "Fashion materials and specifications supporting a garment bill of materials" },
  "private-label-vs-custom-manufacturing": { image: "/images/07.jpeg", imageAlt: "Fashion product development reference for private-label and custom production" },
  "abaya-manufacturer-moq": { image: "/images/08.jpeg", imageAlt: "Modest-wear collection planning reference for abaya order quantities" },
  "prepare-design-for-manufacturer": { image: "/images/09.jpeg", imageAlt: "Fashion concept prepared for a professional manufacturer handoff" },
  "fashion-collection-development": { image: "/images/10.jpeg", imageAlt: "Coordinated fashion collection development reference" },
  "production-management-fashion-brand": { image: "/images/11.jpeg", imageAlt: "Fashion production workflow and collection coordination reference" },
  "fabric-sourcing-checklist-fashion-brand": { image: "/images/12.jpeg", imageAlt: "Fashion fabric sourcing and material-selection reference" },
};

const ACTIVE_POSTS = [...LEGACY_POSTS.filter((post) => post.slug !== "garment-sampling-process-modest-fashion"), ...SEO_POSTS];
export const POSTS = ACTIVE_POSTS.map((post) => ({ ...post, ...(BLOG_IMAGE_OVERRIDES[post.slug] || {}) }));

export function getPost(slug) {
  return POSTS.find((post) => post.slug === slug);
}
